/**
 * DuckDB persistence for GrokHack MMO player/floor state.
 * OWNER: DATABASE team — see server/persistence.OWNER.md
 * Other fleet agents: import public exports only; do not edit this file.
 */
import fs from "node:fs";
import path from "node:path";
import { DuckDBConnection, DuckDBInstance } from "@duckdb/node-api";
import type { FloorState, OnlinePlayer } from "./types.js";
import { dataPath } from "./data-paths.js";
import { LatestSingleFlightWriter } from "./latest-writer.js";

const DEFAULT_DB = dataPath("grokhack.duckdb");

let instance: DuckDBInstance | null = null;
let conn: DuckDBConnection | null = null;
let ready = false;
let closing = false;
let currentPath: string | null = null;
let dbQueue: Promise<void> = Promise.resolve();

const playerTimers = new Map<string, NodeJS.Timeout>();
const floorTimers = new Map<number, NodeJS.Timeout>();
const pendingPlayers = new Map<string, OnlinePlayer>();
const pendingFloors = new Map<number, FloorState>();
const DEBOUNCE_MS = 400;
const worldMetaWriter = new LatestSingleFlightWriter<WorldMeta>(writeWorldMeta, {
  initialDelayMs: DEBOUNCE_MS,
  retryBackoffMs: 1_000,
  onError: (error) => console.error("[db] save world meta:", error),
});
/** Durable schema epoch — bump when adding migrations in applyMigrations(). */
export const SCHEMA_VERSION = 1;
let chatIdSeq = 0;

function enqueueDb<T>(fn: () => Promise<T>): Promise<T> {
  const run = dbQueue.then(fn);
  dbQueue = run.then(
    () => undefined,
    () => undefined
  );
  return run;
}

async function waitForDbQueue(): Promise<void> {
  await dbQueue;
}

export interface WorldMeta {
  worldSeed: number;
  totalTurns: number;
  startedAt: number;
}

export interface PersistedWorld {
  meta: WorldMeta;
  players: OnlinePlayer[];
  floors: FloorState[];
  chatLog: string[];
}

function dbPath(): string {
  const configured = process.env.GROKHACK_DB_PATH?.trim();
  if (configured) return path.resolve(configured);
  return DEFAULT_DB;
}

async function run(sql: string, values?: Record<string, unknown>): Promise<void> {
  if (!conn) throw new Error("persistence not initialized");
  await enqueueDb(() => conn!.run(sql, values));
}

async function queryRows<T extends Record<string, unknown>>(sql: string, values?: Record<string, unknown>): Promise<T[]> {
  if (!conn) throw new Error("persistence not initialized");
  return enqueueDb(async () => {
    const reader = await conn!.runAndReadAll(sql, values);
    const rows = reader.getRowObjectsJson() as T[];
    return rows.map((row) => JSON.parse(JSON.stringify(row)) as T);
  });
}

export async function initPersistence(): Promise<void> {
  const file = dbPath();
  if (ready && currentPath === file) return;
  if (ready) await closePersistence();
  currentPath = file;
  fs.mkdirSync(path.dirname(file), { recursive: true });

  instance = await DuckDBInstance.create(file);
  conn = await instance.connect();

  await run(`
    CREATE TABLE IF NOT EXISTS world_meta (
      id INTEGER PRIMARY KEY,
      world_seed BIGINT NOT NULL,
      total_turns BIGINT NOT NULL,
      started_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS players (
      id VARCHAR PRIMARY KEY,
      player_name VARCHAR NOT NULL,
      name_lower VARCHAR NOT NULL,
      glyph VARCHAR NOT NULL,
      player_kind VARCHAR NOT NULL,
      floor_depth INTEGER NOT NULL,
      game_phase VARCHAR NOT NULL,
      connected INTEGER NOT NULL DEFAULT 0,
      last_active BIGINT NOT NULL,
      score_recorded INTEGER NOT NULL DEFAULT 0,
      state_json VARCHAR NOT NULL,
      explored_json VARCHAR NOT NULL,
      messages_json VARCHAR NOT NULL,
      updated_at BIGINT NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS floors (
      depth INTEGER PRIMARY KEY,
      seed BIGINT NOT NULL,
      state_json VARCHAR NOT NULL,
      updated_at BIGINT NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS chat_log (
      id BIGINT PRIMARY KEY,
      posted_at BIGINT NOT NULL,
      message VARCHAR NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      version INTEGER PRIMARY KEY,
      applied_at BIGINT NOT NULL
    );
  `);

  await run(`CREATE INDEX IF NOT EXISTS idx_players_name_lower ON players(name_lower);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_connected ON players(connected);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_floor_depth ON players(floor_depth);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_game_phase ON players(game_phase);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_last_active ON players(last_active);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_name_lower_active ON players(name_lower, connected, game_phase);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_floors_updated_at ON floors(updated_at);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_chat_log_posted_at ON chat_log(posted_at);`);

  await applyMigrations();

  closing = false;
  ready = true;
  console.log(`[db] DuckDB ready at ${file} (schema v${SCHEMA_VERSION})`);
}

async function appliedMigrationVersions(): Promise<Set<number>> {
  const rows = await queryRows<{ version: number }>(`SELECT version FROM schema_migrations`);
  return new Set(rows.map((r) => Number(r.version)));
}

/**
 * Idempotent migrations. Version 1 = base tables/indexes (created above).
 * Future ALTERs land here with next SCHEMA_VERSION.
 */
async function applyMigrations(): Promise<void> {
  const applied = await appliedMigrationVersions();
  const now = Date.now();

  if (!applied.has(1)) {
    await run(
      `INSERT INTO schema_migrations (version, applied_at) VALUES (1, $applied_at)
       ON CONFLICT (version) DO NOTHING`,
      { applied_at: now }
    );
  }
}

export async function getSchemaVersion(): Promise<number> {
  if (!ready) return 0;
  const rows = await queryRows<{ v: number }>(
    `SELECT COALESCE(MAX(version), 0)::INTEGER AS v FROM schema_migrations`
  );
  return Number(rows[0]?.v ?? 0);
}

function nextChatId(): number {
  chatIdSeq = (chatIdSeq + 1) % 1000;
  return Date.now() * 1000 + chatIdSeq;
}

export function isPersistenceReady(): boolean {
  return ready;
}

function serializePlayer(player: OnlinePlayer) {
  return {
    id: player.id,
    player_name: player.name,
    name_lower: player.name.toLowerCase(),
    glyph: player.glyph,
    player_kind: player.kind,
    floor_depth: player.floorDepth,
    game_phase: player.phase,
    connected: player.connected ? 1 : 0,
    last_active: player.lastActive,
    score_recorded: player.scoreRecorded ? 1 : 0,
    state_json: JSON.stringify(player.state),
    explored_json: JSON.stringify(player.explored),
    messages_json: JSON.stringify(player.messages),
    updated_at: Date.now(),
  };
}

function parseJsonColumn<T>(value: unknown): T {
  if (value == null) return {} as T;
  if (typeof value === "string") return JSON.parse(value) as T;
  return JSON.parse(JSON.stringify(value)) as T;
}

function deserializePlayer(row: Record<string, unknown>): OnlinePlayer {
  return {
    id: String(row.id),
    name: String(row.player_name),
    glyph: String(row.glyph),
    kind: row.player_kind === "agent" ? "agent" : "human",
    state: parseJsonColumn(row.state_json),
    explored: parseJsonColumn(row.explored_json),
    messages: parseJsonColumn(row.messages_json),
    phase: String(row.game_phase) as OnlinePlayer["phase"],
    floorDepth: Number(row.floor_depth),
    connected: Number(row.connected) === 1,
    lastActive: Number(row.last_active),
    scoreRecorded: Number(row.score_recorded) === 1,
  };
}

function serializeFloor(floor: FloorState) {
  return {
    depth: floor.depth,
    seed: floor.seed,
    state_json: JSON.stringify({
      dungeon: floor.dungeon,
      monsters: floor.monsters,
      items: floor.items,
    }),
    updated_at: Date.now(),
  };
}

function deserializeFloor(row: Record<string, unknown>): FloorState {
  const parsed = parseJsonColumn<{
    dungeon: FloorState["dungeon"];
    monsters: FloorState["monsters"];
    items: FloorState["items"];
  }>(row.state_json);
  return {
    depth: Number(row.depth),
    seed: Number(row.seed),
    dungeon: parsed.dungeon,
    monsters: parsed.monsters,
    items: parsed.items,
  };
}

export async function savePlayerNow(player: OnlinePlayer): Promise<void> {
  if (!ready || closing) return;
  pendingPlayers.delete(player.id);
  const row = serializePlayer(player);
  await run(
    `INSERT INTO players (
      id, player_name, name_lower, glyph, player_kind, floor_depth, game_phase, connected,
      last_active, score_recorded, state_json, explored_json, messages_json, updated_at
    ) VALUES (
      $id, $player_name, $name_lower, $glyph, $player_kind, $floor_depth, $game_phase, $connected,
      $last_active, $score_recorded, $state_json, $explored_json, $messages_json, $updated_at
    )
    ON CONFLICT (id) DO UPDATE SET
      player_name = excluded.player_name,
      name_lower = excluded.name_lower,
      glyph = excluded.glyph,
      player_kind = excluded.player_kind,
      floor_depth = excluded.floor_depth,
      game_phase = excluded.game_phase,
      connected = excluded.connected,
      last_active = excluded.last_active,
      score_recorded = excluded.score_recorded,
      state_json = excluded.state_json,
      explored_json = excluded.explored_json,
      messages_json = excluded.messages_json,
      updated_at = excluded.updated_at`,
    row
  );
}

export async function countPlayers(): Promise<number> {
  const rows = await queryRows<{ c: number }>(`SELECT COUNT(*)::INTEGER AS c FROM players`);
  return Number(rows[0]?.c ?? 0);
}

export async function listPlayerNames(): Promise<string[]> {
  const rows = await queryRows<{ player_name: string; name_lower: string }>(
    `SELECT player_name, name_lower FROM players ORDER BY updated_at`
  );
  return rows.map((r) => `${String(r.player_name)}/${String(r.name_lower)}`);
}

export function scheduleSavePlayer(player: OnlinePlayer): void {
  if (!ready || closing) return;
  pendingPlayers.set(player.id, player);
  const existing = playerTimers.get(player.id);
  if (existing) clearTimeout(existing);
  playerTimers.set(
    player.id,
    setTimeout(() => {
      playerTimers.delete(player.id);
      savePlayerNow(player).catch((err) => console.error("[db] save player:", err));
    }, DEBOUNCE_MS)
  );
}

export async function saveFloorNow(floor: FloorState): Promise<void> {
  if (!ready || closing) return;
  pendingFloors.delete(floor.depth);
  const row = serializeFloor(floor);
  await run(
    `INSERT INTO floors (depth, seed, state_json, updated_at)
     VALUES ($depth, $seed, $state_json, $updated_at)
     ON CONFLICT (depth) DO UPDATE SET
       seed = excluded.seed,
       state_json = excluded.state_json,
       updated_at = excluded.updated_at`,
    row
  );
}

export async function loadFloorByDepth(depth: number): Promise<FloorState | null> {
  if (!ready) return null;
  const rows = await queryRows<Record<string, unknown>>(
    `SELECT * FROM floors WHERE depth = $depth LIMIT 1`,
    { depth }
  );
  if (!rows.length) return null;
  return deserializeFloor(rows[0]);
}

export function scheduleSaveFloor(floor: FloorState): void {
  if (!ready || closing) return;
  pendingFloors.set(floor.depth, floor);
  const existing = floorTimers.get(floor.depth);
  if (existing) clearTimeout(existing);
  floorTimers.set(
    floor.depth,
    setTimeout(() => {
      floorTimers.delete(floor.depth);
      saveFloorNow(floor).catch((err) => console.error("[db] save floor:", err));
    }, DEBOUNCE_MS)
  );
}

async function writeWorldMeta(meta: WorldMeta): Promise<void> {
  if (!ready) return;
  await run(
    `INSERT INTO world_meta (id, world_seed, total_turns, started_at, updated_at)
     VALUES (1, $world_seed, $total_turns, $started_at, $updated_at)
     ON CONFLICT (id) DO UPDATE SET
       world_seed = excluded.world_seed,
       total_turns = excluded.total_turns,
       started_at = excluded.started_at,
       updated_at = excluded.updated_at`,
    {
      world_seed: meta.worldSeed,
      total_turns: meta.totalTurns,
      started_at: meta.startedAt,
      updated_at: Date.now(),
    }
  );
}

export async function saveWorldMeta(meta: WorldMeta): Promise<void> {
  if (!ready) return;
  await worldMetaWriter.flush({ ...meta });
}

/** O(1) latest-wins single-flight path for high-frequency turn metadata. */
export function scheduleSaveWorldMeta(meta: WorldMeta): void {
  if (!ready || closing) return;
  worldMetaWriter.schedule({ ...meta });
}

export async function appendChatMessages(messages: string[]): Promise<void> {
  if (!ready || closing || !messages.length) return;
  const now = Date.now();
  for (const message of messages) {
    await run(`INSERT INTO chat_log (id, posted_at, message) VALUES ($id, $posted_at, $message)`, {
      id: nextChatId(),
      posted_at: now,
      message: message.slice(0, 500),
    });
  }
}

export async function loadRecentChat(limit = 200): Promise<string[]> {
  if (!ready) return [];
  const rows = await queryRows<Record<string, unknown>>(
    `SELECT message FROM chat_log ORDER BY posted_at DESC, id DESC LIMIT $limit`,
    { limit: Math.max(1, Math.min(500, limit)) }
  );
  return rows.map((r) => String(r.message)).reverse();
}

async function loadAllPlayerRows(): Promise<Record<string, unknown>[]> {
  return queryRows<Record<string, unknown>>(`SELECT * FROM players ORDER BY updated_at DESC`);
}

export async function loadPlayerByName(name: string): Promise<OnlinePlayer | null> {
  if (!ready) return null;
  const rows = await queryRows<Record<string, unknown>>(
    `SELECT * FROM players
     WHERE name_lower = $lookup
     ORDER BY updated_at DESC
     LIMIT 1`,
    { lookup: name.toLowerCase() }
  );
  if (!rows.length) return null;
  return deserializePlayer(rows[0]);
}

export function isResumablePlayer(player: OnlinePlayer | null | undefined): OnlinePlayer | null {
  if (!player) return null;
  if (player.connected) return null;
  if (player.phase !== "playing" && player.phase !== "inventory") return null;
  return player;
}

export async function loadResumablePlayerByName(name: string): Promise<OnlinePlayer | null> {
  return isResumablePlayer(await loadPlayerByName(name));
}

export async function deletePlayerById(id: string): Promise<void> {
  if (!ready) return;
  await run(`DELETE FROM players WHERE id = $id`, { id });
}

export async function loadWorld(): Promise<PersistedWorld | null> {
  if (!ready) return null;

  const metaRows = await queryRows<Record<string, unknown>>(
    `SELECT world_seed, total_turns, started_at FROM world_meta WHERE id = 1`
  );
  if (!metaRows.length) return null;

  const meta: WorldMeta = {
    worldSeed: Number(metaRows[0].world_seed),
    totalTurns: Number(metaRows[0].total_turns),
    startedAt: Number(metaRows[0].started_at),
  };

  const playerRows = await loadAllPlayerRows();
  const floorRows = await queryRows<Record<string, unknown>>(`SELECT * FROM floors ORDER BY depth`);
  const chatLog = await loadRecentChat(200);

  return {
    meta,
    players: playerRows.map(deserializePlayer).map((p) => ({ ...p, connected: false })),
    floors: floorRows.map(deserializeFloor),
    chatLog,
  };
}

export async function flushPersistence(): Promise<void> {
  for (const timer of playerTimers.values()) clearTimeout(timer);
  for (const timer of floorTimers.values()) clearTimeout(timer);
  playerTimers.clear();
  floorTimers.clear();

  const saves = [
    ...[...pendingPlayers.values()].map((p) => savePlayerNow(p)),
    ...[...pendingFloors.values()].map((f) => saveFloorNow(f)),
    worldMetaWriter.flush(),
  ];
  pendingPlayers.clear();
  pendingFloors.clear();
  await Promise.all(saves);
  await waitForDbQueue();
}

export async function closePersistence(): Promise<void> {
  // Stop accepting new debounced schedules, but force-drain pending writes first.
  // savePlayerNow/saveFloorNow no-op when closing — temporarily allow the drain.
  closing = true;
  for (const timer of playerTimers.values()) clearTimeout(timer);
  for (const timer of floorTimers.values()) clearTimeout(timer);
  playerTimers.clear();
  floorTimers.clear();

  const pendingP = [...pendingPlayers.values()];
  const pendingF = [...pendingFloors.values()];
  pendingPlayers.clear();
  pendingFloors.clear();

  const wasClosing = closing;
  closing = false;
  ready = true;
  try {
    await Promise.all([
      ...pendingP.map((p) => savePlayerNow(p)),
      ...pendingF.map((f) => saveFloorNow(f)),
      worldMetaWriter.flush(),
    ]);
    await waitForDbQueue();
  } finally {
    closing = wasClosing;
  }

  await waitForDbQueue();
  if (conn) {
    conn.closeSync();
    conn = null;
  }
  instance = null;
  ready = false;
  closing = false;
  currentPath = null;
}

/** @internal test helper */
export async function resetPersistenceForTests(): Promise<void> {
  await closePersistence();
}
