/**
 * DuckDB persistence for GrokHack MMO player/floor state.
 * OWNER: DATABASE team — see server/persistence.OWNER.md
 * Other fleet agents: import public exports only; do not edit this file.
 */
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { DuckDBConnection, DuckDBInstance, type DuckDBValue } from "@duckdb/node-api";
import type { FloorState, OnlinePlayer } from "./types.js";
import { dataPath } from "./data-paths.js";
import { LatestSingleFlightWriter } from "./latest-writer.js";

const DEFAULT_DB = dataPath("grokhack.duckdb");

let instance: DuckDBInstance | null = null;
let conn: DuckDBConnection | null = null;
let ready = false;
let closing = false;
let currentPath: string | null = null;
let dbQueue: Promise<void> = Promise.resolve();
let persistencePoisoned: Error | null = null;

const playerTimers = new Map<string, NodeJS.Timeout>();
const floorTimers = new Map<number, NodeJS.Timeout>();
const pendingPlayers = new Map<string, OnlinePlayer>();
const pendingFloors = new Map<number, FloorState>();
const DEBOUNCE_MS = 400;
const worldMetaWriter = new LatestSingleFlightWriter<WorldMeta>(writeWorldMeta, {
  initialDelayMs: DEBOUNCE_MS,
  retryBackoffMs: 1_000,
  onError: (error) => console.error("[db] save world meta:", error),
});
/** Durable schema epoch — bump when adding migrations in applyMigrations(). */
export const SCHEMA_VERSION = 2;
let chatIdSeq = 0;

function enqueueDb<T>(fn: () => Promise<T>): Promise<T> {
  const run = dbQueue.then(fn);
  dbQueue = run.then(
    () => undefined,
    () => undefined
  );
  return run;
}

function activeConnection(expected?: DuckDBConnection): DuckDBConnection {
  if (persistencePoisoned) throw persistencePoisoned;
  if (!conn || (expected && conn !== expected)) throw new Error("persistence not initialized");
  return conn;
}

function poisonPersistenceConnection(connection: DuckDBConnection, cause: unknown): Error {
  const failure = new Error("persistence_connection_poisoned", { cause });
  persistencePoisoned = failure;
  ready = false;
  closing = true;
  if (conn === connection) conn = null;
  try {
    connection.closeSync();
  } catch (closeError) {
    console.error("[db] close poisoned connection:", closeError);
  }
  instance = null;
  return failure;
}

async function waitForDbQueue(): Promise<void> {
  await dbQueue;
}

export interface WorldMeta {
  worldSeed: number;
  totalTurns: number;
  startedAt: number;
}

export interface PersistedWorld {
  meta: WorldMeta;
  players: OnlinePlayer[];
  floors: FloorState[];
  chatLog: string[];
}

function dbPath(): string {
  const configured = process.env.GROKHACK_DB_PATH?.trim();
  if (configured) return path.resolve(configured);
  return DEFAULT_DB;
}

async function run(sql: string, values?: Record<string, DuckDBValue>): Promise<void> {
  const connection = activeConnection();
  await enqueueDb(() => activeConnection(connection).run(sql, values));
}

async function queryRows<T extends Record<string, unknown>>(
  sql: string,
  values?: Record<string, DuckDBValue>,
): Promise<T[]> {
  const connection = activeConnection();
  return enqueueDb(async () => {
    const reader = await activeConnection(connection).runAndReadAll(sql, values);
    const rows = reader.getRowObjectsJson() as T[];
    return rows.map((row) => JSON.parse(JSON.stringify(row)) as T);
  });
}

/** @internal Process-crash seams for the movement snapshot transaction proof. */
export interface MovementTurnPersistenceCrashHooks {
  afterBegin?: () => void;
  afterPlayerWrite?: () => void;
  afterFloorWrite?: (depth: number, index: number) => void;
  afterStaleCommitReceiptPrune?: () => void;
  afterCommitReceiptWrite?: () => void;
  beforeCommit?: () => void;
  afterCommit?: () => void;
  beforeRollback?: () => void;
}

export interface MovementTurnPersistenceIdentity {
  streamId: string;
  operationId: string;
}

function validateMovementTurnPersistenceIdentity(
  input: MovementTurnPersistenceIdentity,
): MovementTurnPersistenceIdentity {
  if (!/^turn_[0-9a-f]{48}$/u.test(input.streamId) ||
      !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(input.operationId)) {
    throw new Error("invalid_movement_turn_persistence_identity");
  }
  return { streamId: input.streamId, operationId: input.operationId };
}

export async function initPersistence(): Promise<void> {
  const file = dbPath();
  if (ready && currentPath === file) return;
  if (ready || conn || instance || persistencePoisoned) await closePersistence();
  persistencePoisoned = null;
  closing = false;
  currentPath = file;
  fs.mkdirSync(path.dirname(file), { recursive: true });

  instance = await DuckDBInstance.create(file);
  conn = await instance.connect();
  try {
    await assertSupportedSchemaVersionBeforeWrites(conn);
  } catch (error) {
    conn.closeSync();
    conn = null;
    instance = null;
    currentPath = null;
    throw error;
  }

  await run(`
    CREATE TABLE IF NOT EXISTS world_meta (
      id INTEGER PRIMARY KEY,
      world_seed BIGINT NOT NULL,
      total_turns BIGINT NOT NULL,
      started_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS players (
      id VARCHAR PRIMARY KEY,
      player_name VARCHAR NOT NULL,
      name_lower VARCHAR NOT NULL,
      glyph VARCHAR NOT NULL,
      player_kind VARCHAR NOT NULL,
      floor_depth INTEGER NOT NULL,
      game_phase VARCHAR NOT NULL,
      connected INTEGER NOT NULL DEFAULT 0,
      last_active BIGINT NOT NULL,
      score_recorded INTEGER NOT NULL DEFAULT 0,
      state_json VARCHAR NOT NULL,
      explored_json VARCHAR NOT NULL,
      messages_json VARCHAR NOT NULL,
      updated_at BIGINT NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS floors (
      depth INTEGER PRIMARY KEY,
      seed BIGINT NOT NULL,
      state_json VARCHAR NOT NULL,
      updated_at BIGINT NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS chat_log (
      id BIGINT PRIMARY KEY,
      posted_at BIGINT NOT NULL,
      message VARCHAR NOT NULL
    );
  `);

  await run(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      version INTEGER PRIMARY KEY,
      applied_at BIGINT NOT NULL
    );
  `);

  await run(`CREATE INDEX IF NOT EXISTS idx_players_name_lower ON players(name_lower);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_connected ON players(connected);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_floor_depth ON players(floor_depth);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_game_phase ON players(game_phase);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_last_active ON players(last_active);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_players_name_lower_active ON players(name_lower, connected, game_phase);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_floors_updated_at ON floors(updated_at);`);
  await run(`CREATE INDEX IF NOT EXISTS idx_chat_log_posted_at ON chat_log(posted_at);`);

  await applyMigrations();

  closing = false;
  ready = true;
  console.log(`[db] DuckDB ready at ${file} (schema v${SCHEMA_VERSION})`);
}

async function appliedMigrationVersions(): Promise<Set<number>> {
  const rows = await queryRows<{ version: number }>(`SELECT version FROM schema_migrations`);
  return new Set(rows.map((r) => Number(r.version)));
}

async function assertSupportedSchemaVersionBeforeWrites(
  connection: DuckDBConnection,
): Promise<void> {
  const tableRows = await readConnectionRows<{ count: number }>(
    connection,
    `SELECT COUNT(*)::INTEGER AS count
       FROM information_schema.tables
      WHERE table_schema = 'main' AND table_name = 'schema_migrations'`,
  );
  if (Number(tableRows[0]?.count ?? 0) === 0) return;
  const versionRows = await readConnectionRows<{ version: number }>(
    connection,
    `SELECT COALESCE(MAX(version), 0)::INTEGER AS version FROM main.schema_migrations`,
  );
  if (Number(versionRows[0]?.version ?? 0) > SCHEMA_VERSION) {
    throw new Error("unsupported_persistence_schema_version");
  }
}

/**
 * Idempotent migrations. Version 1 = base tables/indexes (created above).
 * Version 2 = movement snapshot commit receipts used for cross-store recovery.
 */
async function applyMigrations(): Promise<void> {
  const applied = await appliedMigrationVersions();
  if (Math.max(0, ...applied) > SCHEMA_VERSION) {
    throw new Error("unsupported_persistence_schema_version");
  }
  const now = Date.now();

  if (!applied.has(1)) {
    await run(
      `INSERT INTO schema_migrations (version, applied_at) VALUES (1, $applied_at)
       ON CONFLICT (version) DO NOTHING`,
      { applied_at: now }
    );
  }

  if (!applied.has(2)) {
    await run(`
      CREATE TABLE IF NOT EXISTS movement_turn_commits (
        stream_id VARCHAR NOT NULL,
        operation_id VARCHAR NOT NULL,
        player_id VARCHAR NOT NULL,
        floor_depth_1 INTEGER NOT NULL,
        floor_depth_2 INTEGER,
        snapshot_hash VARCHAR NOT NULL,
        committed_at BIGINT NOT NULL,
        PRIMARY KEY (stream_id, operation_id)
      );
    `);
    await run(
      `INSERT INTO schema_migrations (version, applied_at) VALUES (2, $applied_at)
       ON CONFLICT (version) DO NOTHING`,
      { applied_at: now },
    );
  }
}

export async function getSchemaVersion(): Promise<number> {
  if (!ready) return 0;
  const rows = await queryRows<{ v: number }>(
    `SELECT COALESCE(MAX(version), 0)::INTEGER AS v FROM schema_migrations`
  );
  return Number(rows[0]?.v ?? 0);
}

function nextChatId(): number {
  chatIdSeq = (chatIdSeq + 1) % 1000;
  return Date.now() * 1000 + chatIdSeq;
}

export function isPersistenceReady(): boolean {
  return ready;
}

function serializePlayer(player: OnlinePlayer) {
  return {
    id: player.id,
    player_name: player.name,
    name_lower: player.name.toLowerCase(),
    glyph: player.glyph,
    player_kind: player.kind,
    floor_depth: player.floorDepth,
    game_phase: player.phase,
    connected: player.connected ? 1 : 0,
    last_active: player.lastActive,
    score_recorded: player.scoreRecorded ? 1 : 0,
    state_json: JSON.stringify(player.state),
    explored_json: JSON.stringify(player.explored),
    messages_json: JSON.stringify(player.messages),
    updated_at: Date.now(),
  };
}

function parseJsonColumn<T>(value: unknown): T {
  if (value == null) return {} as T;
  if (typeof value === "string") return JSON.parse(value) as T;
  return JSON.parse(JSON.stringify(value)) as T;
}

function deserializePlayer(row: Record<string, unknown>): OnlinePlayer {
  return {
    id: String(row.id),
    name: String(row.player_name),
    glyph: String(row.glyph),
    kind: row.player_kind === "agent" ? "agent" : "human",
    state: parseJsonColumn(row.state_json),
    explored: parseJsonColumn(row.explored_json),
    messages: parseJsonColumn(row.messages_json),
    phase: String(row.game_phase) as OnlinePlayer["phase"],
    floorDepth: Number(row.floor_depth),
    connected: Number(row.connected) === 1,
    lastActive: Number(row.last_active),
    scoreRecorded: Number(row.score_recorded) === 1,
  };
}

function serializeFloor(floor: FloorState) {
  return {
    depth: floor.depth,
    seed: floor.seed,
    state_json: JSON.stringify({
      dungeon: floor.dungeon,
      monsters: floor.monsters,
      items: floor.items,
      traps: floor.traps,
      eventState: floor.eventState,
      eventBook: floor.eventBook,
    }),
    updated_at: Date.now(),
  };
}

interface MovementTurnCommitRow {
  stream_id: string;
  operation_id: string;
  player_id: string;
  floor_depth_1: number;
  floor_depth_2: number | null;
  snapshot_hash: string;
}

async function readConnectionRows<T extends Record<string, unknown>>(
  connection: DuckDBConnection,
  sql: string,
  values?: Record<string, DuckDBValue>,
): Promise<T[]> {
  const reader = await connection.runAndReadAll(sql, values);
  const rows = reader.getRowObjectsJson() as T[];
  return rows.map((row) => JSON.parse(JSON.stringify(row)) as T);
}

function movementSnapshotHash(
  playerRow: Record<string, unknown>,
  floorRows: readonly Record<string, unknown>[],
): string {
  const player = {
    id: String(playerRow.id),
    playerName: String(playerRow.player_name),
    nameLower: String(playerRow.name_lower),
    glyph: String(playerRow.glyph),
    playerKind: String(playerRow.player_kind),
    floorDepth: Number(playerRow.floor_depth),
    gamePhase: String(playerRow.game_phase),
    connected: Number(playerRow.connected),
    lastActive: Number(playerRow.last_active),
    scoreRecorded: Number(playerRow.score_recorded),
    stateJson: String(playerRow.state_json),
    exploredJson: String(playerRow.explored_json),
    messagesJson: String(playerRow.messages_json),
  };
  const floors = floorRows.map((row) => ({
    depth: Number(row.depth),
    seed: Number(row.seed),
    stateJson: String(row.state_json),
  })).sort((left, right) => left.depth - right.depth);
  return createHash("sha256").update(JSON.stringify({ player, floors }), "utf8").digest("hex");
}

function normalizeMovementTurnCommitRow(row: Record<string, unknown>): MovementTurnCommitRow | null {
  const value: MovementTurnCommitRow = {
    stream_id: String(row.stream_id),
    operation_id: String(row.operation_id),
    player_id: String(row.player_id),
    floor_depth_1: Number(row.floor_depth_1),
    floor_depth_2: row.floor_depth_2 == null ? null : Number(row.floor_depth_2),
    snapshot_hash: String(row.snapshot_hash),
  };
  if (!/^turn_[0-9a-f]{48}$/u.test(value.stream_id) ||
      !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(value.operation_id) ||
      !value.player_id || !Number.isSafeInteger(value.floor_depth_1) ||
      (value.floor_depth_2 !== null && (!Number.isSafeInteger(value.floor_depth_2) ||
        value.floor_depth_2 === value.floor_depth_1)) ||
      !/^[0-9a-f]{64}$/u.test(value.snapshot_hash)) {
    return null;
  }
  return value;
}

async function movementTurnReceiptMatchesStoredSnapshot(
  connection: DuckDBConnection,
  receipt: MovementTurnCommitRow,
): Promise<boolean> {
  const playerRows = await readConnectionRows<Record<string, unknown>>(
    connection,
    `SELECT id, player_name, name_lower, glyph, player_kind, floor_depth, game_phase,
            connected, last_active, score_recorded, state_json, explored_json, messages_json
       FROM players WHERE id = $player_id LIMIT 1`,
    { player_id: receipt.player_id },
  );
  const floorRows = await readConnectionRows<Record<string, unknown>>(
    connection,
    `SELECT depth, seed, state_json FROM floors
      WHERE depth = $floor_depth_1 OR ($floor_depth_2 IS NOT NULL AND depth = $floor_depth_2)
      ORDER BY depth`,
    {
      floor_depth_1: receipt.floor_depth_1,
      floor_depth_2: receipt.floor_depth_2,
    },
  );
  const expectedFloorCount = receipt.floor_depth_2 === null ? 1 : 2;
  return playerRows.length === 1 && floorRows.length === expectedFloorCount &&
    movementSnapshotHash(playerRows[0]!, floorRows) === receipt.snapshot_hash;
}

const UPSERT_PLAYER_SQL = `INSERT INTO players (
    id, player_name, name_lower, glyph, player_kind, floor_depth, game_phase, connected,
    last_active, score_recorded, state_json, explored_json, messages_json, updated_at
  ) VALUES (
    $id, $player_name, $name_lower, $glyph, $player_kind, $floor_depth, $game_phase, $connected,
    $last_active, $score_recorded, $state_json, $explored_json, $messages_json, $updated_at
  )
  ON CONFLICT (id) DO UPDATE SET
    player_name = excluded.player_name,
    name_lower = excluded.name_lower,
    glyph = excluded.glyph,
    player_kind = excluded.player_kind,
    floor_depth = excluded.floor_depth,
    game_phase = excluded.game_phase,
    connected = excluded.connected,
    last_active = excluded.last_active,
    score_recorded = excluded.score_recorded,
    state_json = excluded.state_json,
    explored_json = excluded.explored_json,
    messages_json = excluded.messages_json,
    updated_at = excluded.updated_at`;

const UPSERT_FLOOR_SQL = `INSERT INTO floors (depth, seed, state_json, updated_at)
  VALUES ($depth, $seed, $state_json, $updated_at)
  ON CONFLICT (depth) DO UPDATE SET
    seed = excluded.seed,
    state_json = excluded.state_json,
    updated_at = excluded.updated_at`;

function deserializeFloor(row: Record<string, unknown>): FloorState {
  const parsed = parseJsonColumn<{
    dungeon: FloorState["dungeon"];
    monsters: FloorState["monsters"];
    items: FloorState["items"];
    traps?: FloorState["traps"];
    eventState?: FloorState["eventState"];
    eventBook?: FloorState["eventBook"];
  }>(row.state_json);
  return {
    depth: Number(row.depth),
    seed: Number(row.seed),
    dungeon: parsed.dungeon,
    monsters: parsed.monsters,
    items: parsed.items,
    traps: parsed.traps,
    eventState: parsed.eventState,
    eventBook: parsed.eventBook,
  };
}

export async function savePlayerNow(player: OnlinePlayer): Promise<void> {
  if (persistencePoisoned) throw persistencePoisoned;
  if (!ready || closing) return;
  pendingPlayers.delete(player.id);
  const row = serializePlayer(player);
  await run(UPSERT_PLAYER_SQL, row);
}

export async function countPlayers(): Promise<number> {
  const rows = await queryRows<{ c: number }>(`SELECT COUNT(*)::INTEGER AS c FROM players`);
  return Number(rows[0]?.c ?? 0);
}

export async function listPlayerNames(): Promise<string[]> {
  const rows = await queryRows<{ player_name: string; name_lower: string }>(
    `SELECT player_name, name_lower FROM players ORDER BY updated_at`
  );
  return rows.map((r) => `${String(r.player_name)}/${String(r.name_lower)}`);
}

export function scheduleSavePlayer(player: OnlinePlayer): void {
  if (!ready || closing) return;
  pendingPlayers.set(player.id, player);
  const existing = playerTimers.get(player.id);
  if (existing) clearTimeout(existing);
  playerTimers.set(
    player.id,
    setTimeout(() => {
      playerTimers.delete(player.id);
      savePlayerNow(player).catch((err) => console.error("[db] save player:", err));
    }, DEBOUNCE_MS)
  );
}

export async function saveFloorNow(floor: FloorState): Promise<void> {
  if (persistencePoisoned) throw persistencePoisoned;
  if (!ready || closing) return;
  pendingFloors.delete(floor.depth);
  const row = serializeFloor(floor);
  await run(UPSERT_FLOOR_SQL, row);
}

/**
 * Commits the movement player plus its source/destination floor snapshots as
 * one DuckDB transaction. Row values are captured before entering the shared
 * database queue, and matching debounced writes are cancelled so no older
 * timer can interleave with the atomic snapshot.
 */
export async function saveMovementTurnNow(
  player: OnlinePlayer,
  floors: readonly FloorState[],
  persistenceIdentity: MovementTurnPersistenceIdentity,
  crashHooks: MovementTurnPersistenceCrashHooks = {},
): Promise<void> {
  if (persistencePoisoned) throw persistencePoisoned;
  if (!ready || closing) throw new Error("movement_turn_persistence_unavailable");
  if (floors.length < 1 || floors.length > 2 || new Set(floors.map((floor) => floor.depth)).size !== floors.length) {
    throw new Error("invalid_movement_turn_persistence_floors");
  }
  const identity = validateMovementTurnPersistenceIdentity(persistenceIdentity);

  const playerTimer = playerTimers.get(player.id);
  if (playerTimer) clearTimeout(playerTimer);
  playerTimers.delete(player.id);
  pendingPlayers.delete(player.id);
  for (const floor of floors) {
    const floorTimer = floorTimers.get(floor.depth);
    if (floorTimer) clearTimeout(floorTimer);
    floorTimers.delete(floor.depth);
    pendingFloors.delete(floor.depth);
  }

  const playerRow = serializePlayer(player);
  const floorRows = floors.map(serializeFloor);
  const floorDepths = floors.map((floor) => floor.depth).sort((left, right) => left - right);
  const snapshotHash = movementSnapshotHash(playerRow, floorRows);
  const expectedReceipt: MovementTurnCommitRow = {
    stream_id: identity.streamId,
    operation_id: identity.operationId,
    player_id: player.id,
    floor_depth_1: floorDepths[0]!,
    floor_depth_2: floorDepths[1] ?? null,
    snapshot_hash: snapshotHash,
  };
  const connection = activeConnection();
  await enqueueDb(async () => {
    activeConnection(connection);
    let committed = false;
    try {
      await connection.run("BEGIN TRANSACTION");
      crashHooks.afterBegin?.();
      const existingRows = await readConnectionRows<Record<string, unknown>>(
        connection,
        `SELECT stream_id, operation_id, player_id, floor_depth_1, floor_depth_2, snapshot_hash
           FROM movement_turn_commits
          WHERE stream_id = $stream_id AND operation_id = $operation_id`,
        { stream_id: identity.streamId, operation_id: identity.operationId },
      );
      if (existingRows.length) {
        const existing = normalizeMovementTurnCommitRow(existingRows[0]!);
        if (existingRows.length !== 1 || !existing ||
            JSON.stringify(existing) !== JSON.stringify(expectedReceipt) ||
            !(await movementTurnReceiptMatchesStoredSnapshot(connection, existing))) {
          throw new Error("movement_turn_persistence_receipt_conflict");
        }
        await connection.run(
          `DELETE FROM movement_turn_commits
            WHERE stream_id <> $stream_id OR operation_id <> $operation_id`,
          { stream_id: identity.streamId, operation_id: identity.operationId },
        );
        crashHooks.afterStaleCommitReceiptPrune?.();
        await connection.run("COMMIT");
        committed = true;
        crashHooks.afterCommit?.();
        return;
      }
      // The filesystem journal admits only one global prepared movement. A
      // different receipt is stale cleanup residue from an already completed
      // marker. Prune it inside the new transaction so the table remains in
      // one application-managed slot even when cleanup repeatedly fails after
      // marker removal. enqueueDb serializes every writer around this delete
      // and replacement insert.
      await connection.run(`DELETE FROM movement_turn_commits`);
      crashHooks.afterStaleCommitReceiptPrune?.();
      await connection.run(UPSERT_PLAYER_SQL, playerRow);
      crashHooks.afterPlayerWrite?.();
      for (let index = 0; index < floorRows.length; index += 1) {
        const floor = floors[index]!;
        await connection.run(UPSERT_FLOOR_SQL, floorRows[index]!);
        crashHooks.afterFloorWrite?.(floor.depth, index);
      }
      await connection.run(
        `INSERT INTO movement_turn_commits (
           stream_id, operation_id, player_id, floor_depth_1, floor_depth_2, snapshot_hash, committed_at
         ) VALUES (
           $stream_id, $operation_id, $player_id, $floor_depth_1, $floor_depth_2, $snapshot_hash, $committed_at
         )`,
        { ...expectedReceipt, committed_at: Date.now() },
      );
      crashHooks.afterCommitReceiptWrite?.();
      crashHooks.beforeCommit?.();
      await connection.run("COMMIT");
      committed = true;
      crashHooks.afterCommit?.();
    } catch (error) {
      if (!committed) {
        try {
          crashHooks.beforeRollback?.();
          await connection.run("ROLLBACK");
        } catch (rollbackError) {
          poisonPersistenceConnection(connection, rollbackError);
          throw new AggregateError(
            [error, rollbackError],
            "movement turn transaction rollback failed",
            { cause: rollbackError },
          );
        }
      }
      throw error;
    }
  });
}

/** True only when the receipt and the exact committed player/floor snapshot still match. */
export async function hasMovementTurnCommit(
  persistenceIdentity: MovementTurnPersistenceIdentity,
): Promise<boolean> {
  const identity = validateMovementTurnPersistenceIdentity(persistenceIdentity);
  const connection = activeConnection();
  return enqueueDb(async () => {
    activeConnection(connection);
    const rows = await readConnectionRows<Record<string, unknown>>(
      connection,
      `SELECT stream_id, operation_id, player_id, floor_depth_1, floor_depth_2, snapshot_hash
         FROM movement_turn_commits
        WHERE stream_id = $stream_id AND operation_id = $operation_id`,
      { stream_id: identity.streamId, operation_id: identity.operationId },
    );
    if (rows.length !== 1) return false;
    const receipt = normalizeMovementTurnCommitRow(rows[0]!);
    return receipt !== null && await movementTurnReceiptMatchesStoredSnapshot(connection, receipt);
  });
}

/** Deletes one receipt only after its durable filesystem preparation has been removed. */
export async function deleteMovementTurnCommit(
  persistenceIdentity: MovementTurnPersistenceIdentity,
): Promise<void> {
  const identity = validateMovementTurnPersistenceIdentity(persistenceIdentity);
  await run(
    `DELETE FROM movement_turn_commits
      WHERE stream_id = $stream_id AND operation_id = $operation_id`,
    { stream_id: identity.streamId, operation_id: identity.operationId },
  );
}

/** Boot-only cleanup for receipts whose filesystem preparation already completed. */
export async function clearMovementTurnCommits(): Promise<void> {
  await run(`DELETE FROM movement_turn_commits`);
}

export async function loadFloorByDepth(depth: number): Promise<FloorState | null> {
  if (!ready) return null;
  const rows = await queryRows<Record<string, unknown>>(
    `SELECT * FROM floors WHERE depth = $depth LIMIT 1`,
    { depth }
  );
  if (!rows.length) return null;
  return deserializeFloor(rows[0]);
}

export function scheduleSaveFloor(floor: FloorState): void {
  if (!ready || closing) return;
  pendingFloors.set(floor.depth, floor);
  const existing = floorTimers.get(floor.depth);
  if (existing) clearTimeout(existing);
  floorTimers.set(
    floor.depth,
    setTimeout(() => {
      floorTimers.delete(floor.depth);
      saveFloorNow(floor).catch((err) => console.error("[db] save floor:", err));
    }, DEBOUNCE_MS)
  );
}

async function writeWorldMeta(meta: WorldMeta): Promise<void> {
  if (!ready) return;
  await run(
    `INSERT INTO world_meta (id, world_seed, total_turns, started_at, updated_at)
     VALUES (1, $world_seed, $total_turns, $started_at, $updated_at)
     ON CONFLICT (id) DO UPDATE SET
       world_seed = excluded.world_seed,
       total_turns = excluded.total_turns,
       started_at = excluded.started_at,
       updated_at = excluded.updated_at`,
    {
      world_seed: meta.worldSeed,
      total_turns: meta.totalTurns,
      started_at: meta.startedAt,
      updated_at: Date.now(),
    }
  );
}

export async function saveWorldMeta(meta: WorldMeta): Promise<void> {
  if (!ready) return;
  await worldMetaWriter.flush({ ...meta });
}

/** O(1) latest-wins single-flight path for high-frequency turn metadata. */
export function scheduleSaveWorldMeta(meta: WorldMeta): void {
  if (!ready || closing) return;
  worldMetaWriter.schedule({ ...meta });
}

export async function appendChatMessages(messages: string[]): Promise<void> {
  if (!ready || closing || !messages.length) return;
  const now = Date.now();
  for (const message of messages) {
    await run(`INSERT INTO chat_log (id, posted_at, message) VALUES ($id, $posted_at, $message)`, {
      id: nextChatId(),
      posted_at: now,
      message: message.slice(0, 500),
    });
  }
}

export async function loadRecentChat(limit = 200): Promise<string[]> {
  if (!ready) return [];
  const rows = await queryRows<Record<string, unknown>>(
    `SELECT message FROM chat_log ORDER BY posted_at DESC, id DESC LIMIT $limit`,
    { limit: Math.max(1, Math.min(500, limit)) }
  );
  return rows.map((r) => String(r.message)).reverse();
}

async function loadAllPlayerRows(): Promise<Record<string, unknown>[]> {
  return queryRows<Record<string, unknown>>(`SELECT * FROM players ORDER BY updated_at DESC`);
}

export async function loadPlayerByName(name: string): Promise<OnlinePlayer | null> {
  if (!ready) return null;
  const rows = await queryRows<Record<string, unknown>>(
    `SELECT * FROM players
     WHERE name_lower = $lookup
     ORDER BY updated_at DESC
     LIMIT 1`,
    { lookup: name.toLowerCase() }
  );
  if (!rows.length) return null;
  return deserializePlayer(rows[0]);
}

export function isResumablePlayer(player: OnlinePlayer | null | undefined): OnlinePlayer | null {
  if (!player) return null;
  if (player.connected) return null;
  if (player.phase !== "playing" && player.phase !== "inventory") return null;
  return player;
}

export async function loadResumablePlayerByName(name: string): Promise<OnlinePlayer | null> {
  return isResumablePlayer(await loadPlayerByName(name));
}

export async function deletePlayerById(id: string): Promise<void> {
  if (!ready) return;
  await run(`DELETE FROM players WHERE id = $id`, { id });
}

export async function loadWorld(): Promise<PersistedWorld | null> {
  if (!ready) return null;

  const metaRows = await queryRows<Record<string, unknown>>(
    `SELECT world_seed, total_turns, started_at FROM world_meta WHERE id = 1`
  );
  if (!metaRows.length) return null;

  const meta: WorldMeta = {
    worldSeed: Number(metaRows[0].world_seed),
    totalTurns: Number(metaRows[0].total_turns),
    startedAt: Number(metaRows[0].started_at),
  };

  const playerRows = await loadAllPlayerRows();
  const floorRows = await queryRows<Record<string, unknown>>(`SELECT * FROM floors ORDER BY depth`);
  const chatLog = await loadRecentChat(200);

  return {
    meta,
    players: playerRows.map(deserializePlayer).map((p) => ({ ...p, connected: false })),
    floors: floorRows.map(deserializeFloor),
    chatLog,
  };
}

export async function flushPersistence(): Promise<void> {
  if (persistencePoisoned) throw persistencePoisoned;
  for (const timer of playerTimers.values()) clearTimeout(timer);
  for (const timer of floorTimers.values()) clearTimeout(timer);
  playerTimers.clear();
  floorTimers.clear();

  const saves = [
    ...[...pendingPlayers.values()].map((p) => savePlayerNow(p)),
    ...[...pendingFloors.values()].map((f) => saveFloorNow(f)),
    worldMetaWriter.flush(),
  ];
  pendingPlayers.clear();
  pendingFloors.clear();
  await Promise.all(saves);
  await waitForDbQueue();
}

export async function closePersistence(): Promise<void> {
  // Stop accepting new debounced schedules, but force-drain pending writes first.
  // savePlayerNow/saveFloorNow no-op when closing — temporarily allow the drain.
  closing = true;
  for (const timer of playerTimers.values()) clearTimeout(timer);
  for (const timer of floorTimers.values()) clearTimeout(timer);
  playerTimers.clear();
  floorTimers.clear();

  const pendingP = persistencePoisoned ? [] : [...pendingPlayers.values()];
  const pendingF = persistencePoisoned ? [] : [...pendingFloors.values()];
  pendingPlayers.clear();
  pendingFloors.clear();

  if (!persistencePoisoned && ready) {
    const wasClosing = closing;
    closing = false;
    try {
      await Promise.all([
        ...pendingP.map((p) => savePlayerNow(p)),
        ...pendingF.map((f) => saveFloorNow(f)),
        worldMetaWriter.flush(),
      ]);
      await waitForDbQueue();
    } finally {
      closing = wasClosing;
    }
  }

  await waitForDbQueue();
  if (conn) {
    conn.closeSync();
    conn = null;
  }
  instance = null;
  ready = false;
  closing = false;
  currentPath = null;
  persistencePoisoned = null;
}

/** @internal test helper */
export async function resetPersistenceForTests(): Promise<void> {
  await closePersistence();
}
